# Netflix Data Analytics

### Data Cleaning & Preprocessing

In [5]:
## importing Liabraries

import pandas as pd
import numpy as np

In [9]:
## Loading Datasets
df = pd.read_csv("../data/raw/netflix_titles.csv")

print("Dataset loaded!!")

Dataset loaded!!

In [10]:
## head() shows first 5 data from dataset

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## Understadning Dataset

In [12]:
## shape method shows number of rows and columns available in dataset

df.shape

(8807, 12)

In [14]:
## columns shows name of columns available in dataset

df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [16]:
## info gives overall base information of dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [18]:
## describe method gives mathemetical information of data

df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [20]:
## this method gives total count of null values available in dataset

df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

## Handling Null Values

In [38]:
## fill Null Values of country column
df["country"] = df["country"].fillna("Unknown")

## fill Null Values of cast column
df["cast"] = df["cast"].fillna("Not Listed")

## fill Null Values of director column
df["director"] = df["director"].fillna("Unknown")

## filling dates in blank column
import numpy as np

random_dates = np.random.choice(df["date_added"].dropna(), size=df["date_added"].isnull().sum())

df.loc[df["date_added"].isnull(), "date_added"] = random_dates

## fill Null Values of country column
df["rating"] = df["rating"].fillna("Unknown")

## fill Null Values of country column
df["duration"] = df["duration"].fillna("Not Defined")

In [39]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [48]:
## delete duplicate values

df.drop_duplicates(inplace = True)

In [49]:
## change date in proper format

df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)
df["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[us]

## Feature Engineering

### New features were created to improve analytical capability and trend analysis.

In [50]:
df["content_age"] = 2026 - df["release_year"]

In [51]:
df["decade"] = (df["release_year"] // 10) * 10

In [52]:
df["month_added"] = df["date_added"].dt.month

In [53]:
df["year_added"] = df["date_added"].dt.year

In [56]:
## Creating new cleaned dataset csv file

df.to_csv("../data/cleaned/cleaned_netflix.csv", index=False)
print("CSV Saved!!!")

CSV Saved!!!