# 3. SQL Analysis

In [2]:
# Importing Liabraries

import pandas as pd
import sqlite3

print("Liabraries imported sucessfully!!")

Liabraries imported sucessfully!!

In [3]:
# loading dataset file

df = pd.read_csv("../data/cleaned/cleaned_netflix.csv")
print("File loaded!")

File loaded!

In [5]:
# Creating netflix database

conn = sqlite3.connect("../sql/netflix.db")
print("DB Created!")

DB Created!

In [11]:
# Connecitng with netflix database --> taking CSV data into netflix database

df.to_sql("netflix", conn, if_exists="replace",index=False)

8807

In [12]:
# Checking data available in netflix database

query = "SELECT * FROM netflix LIMIT 5"

pd.read_sql(query, conn)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,content_age,decade,month_added,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Listed,United States,25-09-2021,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6,2020,9,2021
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5,2020,9,2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,24-09-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5,2020,9,2021
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Listed,Unknown,24-09-2021,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5,2020,9,2021
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5,2020,9,2021

Count Movies vs TV Shows

In [14]:
query1 = """SELECT type, 
COUNT(*) AS total_content 
FROM netflix 
GROUP BY type"""

pd.read_sql(query1, conn)

      type  total_content
0    Movie           6131
1  TV Show           2676

TOP 10 Countries

In [19]:
query2 = """ SELECT country,
COUNT(*) AS total_country
FROM netflix
GROUP BY country
ORDER BY total_country DESC
LIMIT 10"""

pd.read_sql(query2, conn)

          country  total_country
0   United States           2818
1           India            972
2         Unknown            831
3  United Kingdom            419
4           Japan            245
5     South Korea            199
6          Canada            181
7           Spain            145
8          France            124
9          Mexico            110